<?php
echo "<h1>post index</h1>";

if ($posts->count() >= 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>message</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Posts quantity: <?php echo $posts->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($posts as $post) { ?>
            <tr>
                <td><?php echo $post->id; ?></td>
                <td><?php echo $post->message; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
